### ISSUE TITLE
Correções - avaliação prévia

### ISSUE THREAD

**Issue by tiagoboeing** [tiagoboeing/compiladores#15]
Realizar ajustes de acordo com [correções da avaliação prévia.](https://github.com/tiagoboeing/compiladores/wiki/Retorno-avalia%C3%A7%C3%A3o-pr%C3%A9via-(interface---l%C3%A9xico---sint%C3%A1tico))

# To-Do
- [x] Ajustar `questao_a` de acordo com `identificador`: **0,6 de 1**
- [x] Comentário de linha ignorado (`questao_f`) : **0 de 0,5**
- [x] Comentário de bloco ignorado (`questao_g`): **0 de 1**
- [x] Necessário gerar código novamente no GALS

## Ajuste questao_a 1ee1e00a17865ecb648f9d2cccb8662e2e17ac3f
![image](https://user-images.githubusercontent.com/3449932/59320609-64ca9000-8ca5-11e9-9741-08ae913a7e77.png)

- [x] Necessário gerar código novamente no GALS

## Erro 03 3ed56501de5beffe5793133d2cf5c48229720fc5 
Corrige mensagens de erros de acordo com correções.

![image](https://user-images.githubusercontent.com/3449932/59320362-78c1c200-8ca4-11e9-9edb-14b1cce51f5f.png)

**Comment by tiagoboeing** [comment]
Vamos continuar todas estas discussões na issue #19
